name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create temp local.properties
        env:
          TEMP_KEY: ${{ secrets.TEMP_LOCAL_PROPERTIES }}
        run: echo TEMP_KEY="$TEMP_KEY" > ./local.properties

      - name: Build with gradle
        run: ./gradlew build
